-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 21:45:12 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` BIGINT(11) NOT NULL COMMENT '用户名',
  `password` CHAR(32) NOT NULL COMMENT '密码',
  `create_time` INT(10) NOT NULL COMMENT '创建时间',
  `nick_name` VARCHAR(50) NULL,
  `uuid` CHAR(38) NOT NULL,
  `email` VARCHAR(30) NULL COMMENT '邮箱',
  `status` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1启用，2禁用',
  `last_time` INT(10) NOT NULL COMMENT '最后登录时间',
  `wechat_openid` VARCHAR(64) NULL COMMENT '微信openid',
  `qq_openid` VARCHAR(64) NULL COMMENT 'qqopenid',
  `sina_openid` VARCHAR(64) NULL COMMENT '微博openid',
  `cate` TINYINT(1) NOT NULL DEFAULT 2 COMMENT '1为后台管理员，2及以上是普通会员',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shop`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `access` VARCHAR(1000) NULL,
  `status` CHAR(1) NOT NULL DEFAULT '1' COMMENT '1启用，2禁用',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '角色组';


-- -----------------------------------------------------
-- Table `shop`.`user_access`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user_access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT '名称',
  `name` VARCHAR(45) NOT NULL COMMENT '路径',
  `status` CHAR(1) NOT NULL,
  `pid` INT NULL DEFAULT 0,
  `route` VARCHAR(45) NULL COMMENT '路由',
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `shop`.`user_role_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user_role_group` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_user_role_user_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_user_role_user_idx` (`user_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
